FROM node:17-alpine as builder
#/app è la cartella che conterrà tutti i file all'interno del container
WORKDIR '/app' 
#Copia e installa le dipendenze, se non ci sono cambiamenti docker recupera questa immagine dalla cache
COPY ./package.json ./   
RUN npm install
RUN npm i -g @angular/cli
#A questo punto copia il restante contenuto della cartella
COPY . .
RUN ng build foo --prod

FROM nginx
EXPOSE 80 
COPY --from=builder /app/dist/foo /usr/share/nginx/html